name: "DOCKER Build and Deploy Site"

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:
    inputs:
      name:
        description: 'Who triggered this build?'
        required: true
        default: 'Maintainer (via GitHub)'
      reset:
        description: 'Reset cached markdown files'
        required: false
        default: false
        type: boolean
jobs:
  full-build:
    name: "Build Full Site"

    # 2024-10-01: ubuntu-latest is now 24.04 and R is not installed by default in the runner image
    # pin to 22.04 for now
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: write
      pages: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv/
    steps:
      - name: "Checkout Lesson"
        uses: actions/checkout@v4

      - name: "Docker Build Site"
        uses: addnab/docker-run-action@v3
        with:
            image: carpentries/workbench-docker:0.0.1-alpha
            options: -v ${{ github.workspace }}:/home/rstudio/lesson
            shell: Rscript {0}
            run: |
              reset <- "${{ github.event.inputs.reset }}" == "true"
              setwd("/home/rstudio/lesson")
              sandpaper::package_cache_trigger(TRUE)
              sandpaper:::ci_deploy(reset = reset)
        
